---
- name: Update system packages
  package:
    name: '*'
    state: latest
  when: ansible_os_family == "RedHat"

- name: Install common packages
  package:
    name:
      - wget
      - curl
      - unzip
      - tar
      - python3
      - python3-pip
    state: present
  when: ansible_os_family == "RedHat"

- name: Ensure /opt/networker directory exists
  file:
    path: /opt/networker
    state: directory
    mode: '0755'
    owner: root
    group: root

- name: Set system timezone
  timezone:
    name: UTC

- name: Configure firewall for NetWorker
  firewalld:
    port: "{{ item }}"
    permanent: yes
    state: enabled
    immediate: yes
  loop:
    - 7937-7938/tcp
    - 111/tcp
    - 2049/tcp
  when: ansible_os_family == "RedHat"
  ignore_errors: yes

- name: Ensure hostname is in /etc/hosts
  lineinfile:
    path: /etc/hosts
    line: "{{ ansible_default_ipv4.address }} {{ ansible_hostname }} {{ ansible_fqdn }}"
    state: present